#!/bin/bash

while [ true ] ; do
rm -rf `find /tmp/ingress-screenshot-* -mmin +10 -type d`
rm -rf `find /tmp/irmbot-semaphore-* -mmin +30 -type d`
python3 ./rtmbot.py
sleep 30
echo "Recycling bot ..." | mailx -s "Ingress Screenshotbot recycling" marx@cxm.de marx@cxm.de
done
